#!/usr/bin/env python3
"""fake_cctv.py — turn a local video file into a looping "live" RTSP camera.

Wraps ffmpeg so IBVAP (or any RTSP consumer) can be tested without real CCTV
hardware. The feed loops forever, and if ffmpeg exits it is restarted
automatically, so the stream keeps behaving like an always-on camera.

Subcommands:
  sample [OUTPUT]   generate a synthetic test video (lavfi testsrc2)
  run SOURCE        run the stream in the foreground (Ctrl+C to stop)
  start SOURCE      start the stream in the background (survives the shell)
  status            show whether the stream is running (+ recent log lines)
  stop              stop the background stream

Modes (--mode):
  mediamtx  (default) ffmpeg pushes into a MediaMTX server (single small
            binary, zero config) so any number of clients can watch
            simultaneously - e.g. the IBVAP backend AND rtsp_viewer.py.
  listen    ffmpeg itself is the RTSP server; no extra software needed.
            Serves exactly ONE client at a time. NOTE: on some ffmpeg
            builds (e.g. 8.x on Windows) listen mode never opens the
            listening port - if 8554 stays closed, use mediamtx mode.

Examples:
  python scripts/fake_cctv.py sample samples/demo.mp4
  python scripts/fake_cctv.py start samples/demo.mp4
  python scripts/fake_cctv.py status
  python scripts/rtsp_viewer.py        # watch rtsp://127.0.0.1:8554/cctv
  python scripts/fake_cctv.py stop
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
STATE_DIR = SCRIPT_DIR / ".fake_cctv"
STATE_FILE = STATE_DIR / "state.json"
LOG_FILE = STATE_DIR / "stream.log"
MTX_CONFIG_FILE = STATE_DIR / "mediamtx.yml"

DEFAULT_PORT = 8554
DEFAULT_NAME = "cctv"
DEFAULT_BIND = "0.0.0.0"

# H.264 settings tuned for a low-latency, RTSP-friendly "camera" feed.
VIDEO_ARGS = [
    "-c:v", "libx264",
    "-preset", "ultrafast",
    "-tune", "zerolatency",
    "-profile:v", "baseline",
    "-pix_fmt", "yuv420p",
    "-g", "25",            # keyframe every second (25 fps input)
    "-bf", "0",            # no B-frames -> lower latency
    "-crf", "28",
]


def die(msg: str, code: int = 1) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(code)


def require_ffmpeg() -> None:
    if shutil.which("ffmpeg") is None:
        die(
            "ffmpeg not found on PATH. Install it first:\n"
            "  winget install Gyan.FFmpeg      (Windows)\n"
            "  choco install ffmpeg  |  scoop install ffmpeg\n"
            "  sudo apt install ffmpeg          (Debian/Ubuntu)\n"
            "  brew install ffmpeg              (macOS)"
        )


def port_open(port: int, host: str = "127.0.0.1") -> bool:
    """True if something is already listening on 127.0.0.1:port."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(0.5)
        return sock.connect_ex((host, port)) == 0


def load_state() -> dict | None:
    try:
        return json.loads(STATE_FILE.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def pid_alive(pid: int) -> bool:
    if os.name == "nt":
        result = subprocess.run(
            ["tasklist", "/FI", f"PID eq {pid}", "/NH"],
            capture_output=True, text=True,
        )
        return str(pid) in (result.stdout or "")
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False


def client_url(port: int, name: str) -> str:
    """The URL consumers (viewer / IBVAP backend) connect to."""
    return f"rtsp://127.0.0.1:{port}/{name}"


def check_source(source: str) -> Path:
    path = Path(source)
    if not path.is_file():
        die(
            f"input video not found: {path}\n"
            f"Tip: create one with  python {Path(__file__).name} sample {path}"
        )
    return path


def ensure_mtx_config(name: str, port: int) -> Path:
    """Write a minimal MediaMTX config exposing just our stream path.

    Without a config file MediaMTX v1.x runs with an *empty* configuration
    (no paths at all) and rejects publishers with "path 'cctv' is not
    configured" / HTTP 400.
    """
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    MTX_CONFIG_FILE.write_text(
        "# Minimal MediaMTX configuration generated by scripts/fake_cctv.py\n"
        "api: no\n"
        "rtsp: yes\n"
        f"rtspAddress: :{port}\n"
        "rtmp: no\n"
        "hls: no\n"
        "webrtc: no\n"
        "srt: no\n"
        "moq: no\n"
        "paths:\n"
        f"  {name}:\n",
        encoding="utf-8",
    )
    return MTX_CONFIG_FILE


def resolve_mediamtx(mediamtx_bin: str | None) -> str:
    """Locate the MediaMTX binary (PATH, --mediamtx-bin, or tools/mediamtx/)."""
    server = mediamtx_bin or shutil.which("mediamtx") or shutil.which("rtsp-simple-server")
    if not server:
        local_mtx = PROJECT_DIR / "tools" / "mediamtx" / (
            "mediamtx.exe" if os.name == "nt" else "mediamtx"
        )
        if local_mtx.is_file():
            server = str(local_mtx)
    if not server:
        die(
            "mode 'mediamtx' needs the MediaMTX binary:\n"
            "  download it from https://github.com/bluenviron/mediamtx/releases\n"
            "  and put it on PATH, pass --mediamtx-bin, or place it at\n"
            "  tools/mediamtx/mediamtx(.exe)"
        )
    return server


def build_ffmpeg_cmd(source: Path, mode: str, bind: str, port: int, name: str) -> list[str]:
    """ffmpeg command that re-streams `source` as a looping RTSP feed."""
    cmd = [
        "ffmpeg", "-hide_banner", "-loglevel", "warning",
        "-re",                 # read at native frame rate -> "live" pacing
        "-stream_loop", "-1",  # loop the input forever
        "-i", str(source),
        "-an",                 # CCTV feeds are silent; drop audio
        *VIDEO_ARGS,
        "-f", "rtsp",
        "-rtsp_transport", "tcp",
    ]
    if mode == "listen":
        # ffmpeg IS the RTSP server: bind the port and wait for (one) client.
        cmd += ["-rtsp_flags", "listen", f"rtsp://{bind}:{port}/{name}"]
    else:
        # push into a MediaMTX server that hosts the feed for many clients
        cmd += [client_url(port, name)]
    return cmd

# ------------------------------------------------------------- supervision
def supervise(
    mode: str, bind: str, port: int, name: str,
    source: Path, mediamtx_bin: str | None, log,
) -> None:
    """Run ffmpeg forever, restarting it whenever it exits (Ctrl+C to stop)."""
    server_proc: subprocess.Popen | None = None
    proc: subprocess.Popen | None = None
    try:
        mtx_config = ensure_mtx_config(name, port) if mode == "mediamtx" else None

        shown_url = client_url(port, name) if mode == "mediamtx" else f"rtsp://{bind}:{port}/{name}"
        print(
            f"[fake-cctv] serving {shown_url}  (mode={mode}, source={source.name})",
            file=log, flush=True,
        )
        while True:
            # (Re)start MediaMTX whenever it is not running; ffmpeg push
            # attempts fail harmlessly until the server accepts again.
            if mode == "mediamtx" and not port_open(port):
                if server_proc is None or server_proc.poll() is not None:
                    print(
                        f"[fake-cctv] starting MediaMTX: {mediamtx_bin}",
                        file=log, flush=True,
                    )
                    server_proc = subprocess.Popen(
                        [mediamtx_bin, str(mtx_config)], stdout=log, stderr=log,
                    )
                    time.sleep(1.0)
            proc = subprocess.Popen(
                build_ffmpeg_cmd(source, mode, bind, port, name),
                stdout=log, stderr=log,
            )
            code = proc.wait()
            print(
                f"[fake-cctv] ffmpeg exited (code {code}) - restarting in 1s",
                file=log, flush=True,
            )
            time.sleep(1.0)
    except KeyboardInterrupt:
        print("\n[fake-cctv] stopping stream ...", file=log, flush=True)
    finally:
        for p in (proc, server_proc):
            if p is not None and p.poll() is None:
                p.terminate()
        for p in (proc, server_proc):
            if p is not None and p.poll() is None:
                try:
                    p.wait(timeout=3)
                except subprocess.TimeoutExpired:
                    p.kill()


def cmd_run(args) -> None:
    source = check_source(args.source)
    require_ffmpeg()
    if port_open(args.port):
        die(
            f"port {args.port} is already in use - is a stream already running? "
            "(try 'status'/'stop', or pick another --port)"
        )
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    LOG_FILE.write_bytes(b"")
    mtx_bin = resolve_mediamtx(args.mediamtx_bin) if args.mode == "mediamtx" else None
    supervise(args.mode, args.bind, args.port, args.name, source, mtx_bin, sys.stdout)


def cmd_watchdog(args) -> None:
    """Background supervisor started by `start` (not meant to run by hand)."""
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    with LOG_FILE.open("a", encoding="utf-8", buffering=1) as log:
        log.write(f"\n=== watchdog started {time.strftime('%Y-%m-%d %H:%M:%S')} ===\n")
        try:
            supervise(
                args.mode, args.bind, args.port, args.name,
                Path(args.source), args.mediamtx_bin, log,
            )
        finally:
            log.write("\n=== watchdog stopped ===\n")


def cmd_start(args) -> None:
    source = check_source(args.source)
    require_ffmpeg()
    state = load_state()
    if state and pid_alive(state["pid"]):
        die(
            f"stream already running (pid {state['pid']}, {state.get('url')}) "
            "- use 'status' or 'stop'"
        )
    if port_open(args.port):
        die(f"port {args.port} is already in use by another process - pick another --port")
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    LOG_FILE.write_bytes(b"")

    cmd = [
        sys.executable, str(Path(__file__).resolve()), "_watchdog",
        "--mode", args.mode, "--bind", args.bind,
        "--port", str(args.port), "--name", args.name,
        "--source", str(source.resolve()),
    ]
    if args.mode == "mediamtx":
        cmd += ["--mediamtx-bin", resolve_mediamtx(args.mediamtx_bin)]

    if os.name == "nt":
        # DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP: survives the shell closing
        popen_kwargs = {"creationflags": 0x00000008 | 0x00000200}
    else:
        popen_kwargs = {"start_new_session": True}
    proc = subprocess.Popen(
        cmd, stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        **popen_kwargs,
    )
    STATE_FILE.write_text(
        json.dumps(
            {
                "pid": proc.pid,
                "mode": args.mode,
                "url": client_url(args.port, args.name),
                "source": str(source),
                "started": time.strftime("%Y-%m-%d %H:%M:%S"),
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    time.sleep(1.5)
    if not pid_alive(proc.pid):
        tail = LOG_FILE.read_text(encoding="utf-8", errors="replace").strip().splitlines()[-8:]
        print("watchdog exited immediately - log tail:", file=sys.stderr)
        for line in tail:
            print("  " + line, file=sys.stderr)
        STATE_FILE.unlink(missing_ok=True)
        sys.exit(1)
    print(f"[fake-cctv] started (pid {proc.pid}) -> {client_url(args.port, args.name)}")
    print(f"[fake-cctv] log file: {LOG_FILE}")

def cmd_stop(args) -> None:
    state = load_state()
    if not state:
        print("stopped (no state file - the stream was not started by this script)")
        return
    pid = state["pid"]
    if not pid_alive(pid):
        STATE_FILE.unlink(missing_ok=True)
        print(f"stopped (process {pid} was already gone; removed stale state)")
        return
    if os.name == "nt":
        # /T kills the whole tree (watchdog + ffmpeg), /F = force
        subprocess.run(["taskkill", "/PID", str(pid), "/T", "/F"], capture_output=True)
    else:
        import signal

        try:
            os.killpg(os.getpgid(pid), signal.SIGTERM)
        except OSError:
            os.kill(pid, signal.SIGTERM)
    for _ in range(20):
        if not pid_alive(pid):
            break
        time.sleep(0.25)
    STATE_FILE.unlink(missing_ok=True)
    print(f"stopped (pid {pid}, {state.get('url', '')})")


def cmd_status(args) -> None:
    state = load_state()
    if not state:
        print("stopped (never started on this machine)")
        return
    alive = pid_alive(state["pid"])
    print(f"mode   : {state.get('mode')}")
    print(f"url    : {state.get('url')}")
    print(f"source : {state.get('source')}")
    print(f"pid    : {state['pid']}  (started {state.get('started')})")
    print(f"state  : {'RUNNING' if alive else 'STOPPED'}")
    if LOG_FILE.exists():
        lines = LOG_FILE.read_text(encoding="utf-8", errors="replace").strip().splitlines()
        recent = [line for line in lines[-6:] if line.strip()]
        if recent:
            print("recent log:")
            for line in recent:
                print("  " + line)


def cmd_sample(args) -> None:
    require_ffmpeg()
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-f", "lavfi", "-i", f"testsrc2=size={args.size}:rate=25",
        "-t", str(args.duration),
        "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p",
        str(out),
    ]
    print(f"[fake-cctv] generating {args.duration}s test clip ({args.size}) -> {out}")
    result = subprocess.run(cmd)
    if result.returncode != 0:
        die("ffmpeg failed to generate the sample clip")
    print(f"[fake-cctv] sample video ready: {out}")


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="fake_cctv.py",
        description="Re-stream a local video file as a looping RTSP 'CCTV camera' via ffmpeg.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    def add_stream_args(sp) -> None:
        sp.add_argument(
            "--mode", choices=["listen", "mediamtx"], default="mediamtx",
            help="mediamtx = real RTSP server, many clients (recommended; needs "
                 "the mediamtx binary on PATH); listen = ffmpeg itself serves 1 "
                 "client (no extra software; never binds a port on some builds)",
        )
        sp.add_argument("--bind", default=DEFAULT_BIND,
                        help="listen mode bind address (default: %(default)s)")
        sp.add_argument("--port", type=int, default=DEFAULT_PORT)
        sp.add_argument("--name", default=DEFAULT_NAME,
                        help="stream path -> rtsp://host:PORT/NAME (default: %(default)s)")
        sp.add_argument("--mediamtx-bin", default=None,
                        help="path to the mediamtx binary (mode=mediamtx)")

    sp = sub.add_parser("sample", help="generate a synthetic test video with ffmpeg")
    sp.add_argument("output", nargs="?", default=str(PROJECT_DIR / "samples" / "sample.mp4"))
    sp.add_argument("--duration", type=int, default=30, help="seconds (default: %(default)s)")
    sp.add_argument("--size", default="640x360")
    sp.set_defaults(func=cmd_sample)

    for cmd_name, help_text, func in (
        ("run", "run the stream in the foreground (Ctrl+C to stop)", cmd_run),
        ("start", "run the stream in the background (survives the shell)", cmd_start),
    ):
        sp = sub.add_parser(cmd_name, help=help_text)
        sp.add_argument("source", help="path to a local video file (.mp4, .mkv, ...)")
        add_stream_args(sp)
        sp.set_defaults(func=func)

    sp = sub.add_parser("status", help="show whether the stream is running")
    sp.set_defaults(func=cmd_status)
    sp = sub.add_parser("stop", help="stop the background stream")
    sp.set_defaults(func=cmd_stop)

    sp = sub.add_parser("_watchdog", help=argparse.SUPPRESS)
    add_stream_args(sp)
    sp.add_argument("--source", required=True)
    sp.set_defaults(func=cmd_watchdog)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()


